include:
  - path:
      - sensitive-data-archive/.github/integration/sda-s3-integration.yml
    project_directory: sensitive-data-archive/.github/integration
    env_file:
      - configuration/sensitive-data-archive/.env
